<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Java Exceptions | Cong's Log</title><meta name=keywords content="Java"><meta name=description content='Exception-handling
假如调用了一个不是自己写的方法, 该方法执行某些有风险的任务(当然,自己写的也可能会有风险),可能会在运行期间出状况,那么就必须认识到该方法是有风险的, 要写出可以在发生状况时做出应对的代码.
当程序出现错误时，假如继续运行下去已经没有意义（或者根本不可能继续），那么我们就想要中断正常的控制流程 - throws an exception。

Throwing Exceptions
比如当想从某ArrayMap中提取某个不存在的键值时, java自动抛出一个implicit exception
$ java ExceptionDemo
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
at ArrayMap.get(ArrayMap.java:38)
at ExceptionDemo.main(ExceptionDemo.java:6)
如果想让自己的程序抛出更详细的信息, 可以在程序中加入explicit exception
public V get(K key) {
    intlocation = findKey(key);
    if(location < 0) {
        throw newIllegalArgumentException("Key " + key + " does not exist in map."\);
    }
    return values[findKey(key)];
}
$java ExceptionDemo
Exception in thread "main" java.lang.IllegalArgumentException: Key yolp does not exist in map.
at ArrayMap.get(ArrayMap.java:40)
at ExceptionDemo.main(ExceptionDemo.java:6)
Catch Exceptions
单纯 throw exception 会导致代码崩溃。但是通过 try - catch “捕捉”异常(RuntimeException 是 Java object), 可以防止程序崩溃。'><meta name=author content="Cong Chan"><link rel=canonical href=https://congchan.github.io/posts/java-exceptions/><link crossorigin=anonymous href=/assets/css/stylesheet.1f908d890a7e84b56b73a7a0dc6591e6e3f782fcba048ce1eb46319195bedaef.css integrity="sha256-H5CNiQp+hLVrc6eg3GWR5uP3gvy6BIzh60YxkZW+2u8=" rel="preload stylesheet" as=style><link rel=icon href=https://congchan.github.io/favicons/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://congchan.github.io/favicons/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://congchan.github.io/favicons/favicon-32x32.png><link rel=apple-touch-icon href=https://congchan.github.io/favicons/apple-touch-icon.png><link rel=mask-icon href=https://congchan.github.io/%3Clink%20/%20abs%20url%3E><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><link rel=alternate hreflang=en href=https://congchan.github.io/posts/java-exceptions/><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css integrity=sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X crossorigin=anonymous><script defer src=https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js integrity=sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4 crossorigin=anonymous></script><script defer src=https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js integrity=sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa crossorigin=anonymous onload='renderMathInElement(document.body,{delimiters:[{left:"$$",right:"$$",display:!0},{left:"\\[",right:"\\]",display:!0},{left:"$",right:"$",display:!1},{left:"\\(",right:"\\)",display:!1}]})'></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-6T0DPR6SMC"></script><script>var dnt,doNotTrack=!1;if(!1&&(dnt=navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack,doNotTrack=dnt=="1"||dnt=="yes"),!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-6T0DPR6SMC")}</script><meta property="og:url" content="https://congchan.github.io/posts/java-exceptions/"><meta property="og:site_name" content="Cong's Log"><meta property="og:title" content="Java Exceptions"><meta property="og:description" content='Exception-handling 假如调用了一个不是自己写的方法, 该方法执行某些有风险的任务(当然,自己写的也可能会有风险),可能会在运行期间出状况,那么就必须认识到该方法是有风险的, 要写出可以在发生状况时做出应对的代码.
当程序出现错误时，假如继续运行下去已经没有意义（或者根本不可能继续），那么我们就想要中断正常的控制流程 - throws an exception。
Throwing Exceptions 比如当想从某ArrayMap中提取某个不存在的键值时, java自动抛出一个implicit exception
$ java ExceptionDemo Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1 at ArrayMap.get(ArrayMap.java:38) at ExceptionDemo.main(ExceptionDemo.java:6) 如果想让自己的程序抛出更详细的信息, 可以在程序中加入explicit exception
public V get(K key) { intlocation = findKey(key); if(location < 0) { throw newIllegalArgumentException("Key " + key + " does not exist in map."\); } return values[findKey(key)]; } $java ExceptionDemo Exception in thread "main" java.lang.IllegalArgumentException: Key yolp does not exist in map. at ArrayMap.get(ArrayMap.java:40) at ExceptionDemo.main(ExceptionDemo.java:6) Catch Exceptions 单纯 throw exception 会导致代码崩溃。但是通过 try - catch “捕捉”异常(RuntimeException 是 Java object), 可以防止程序崩溃。'><meta property="og:locale" content="en"><meta property="og:type" content="article"><meta property="article:section" content="posts"><meta property="article:published_time" content="2017-05-29T00:00:00+00:00"><meta property="article:modified_time" content="2017-05-29T00:00:00+00:00"><meta property="article:tag" content="Java"><meta name=twitter:card content="summary"><meta name=twitter:title content="Java Exceptions"><meta name=twitter:description content='Exception-handling
假如调用了一个不是自己写的方法, 该方法执行某些有风险的任务(当然,自己写的也可能会有风险),可能会在运行期间出状况,那么就必须认识到该方法是有风险的, 要写出可以在发生状况时做出应对的代码.
当程序出现错误时，假如继续运行下去已经没有意义（或者根本不可能继续），那么我们就想要中断正常的控制流程 - throws an exception。

Throwing Exceptions
比如当想从某ArrayMap中提取某个不存在的键值时, java自动抛出一个implicit exception
$ java ExceptionDemo
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
at ArrayMap.get(ArrayMap.java:38)
at ExceptionDemo.main(ExceptionDemo.java:6)
如果想让自己的程序抛出更详细的信息, 可以在程序中加入explicit exception
public V get(K key) {
    intlocation = findKey(key);
    if(location < 0) {
        throw newIllegalArgumentException("Key " + key + " does not exist in map."\);
    }
    return values[findKey(key)];
}
$java ExceptionDemo
Exception in thread "main" java.lang.IllegalArgumentException: Key yolp does not exist in map.
at ArrayMap.get(ArrayMap.java:40)
at ExceptionDemo.main(ExceptionDemo.java:6)
Catch Exceptions
单纯 throw exception 会导致代码崩溃。但是通过 try - catch “捕捉”异常(RuntimeException 是 Java object), 可以防止程序崩溃。'><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"https://congchan.github.io/posts/"},{"@type":"ListItem","position":2,"name":"Java Exceptions","item":"https://congchan.github.io/posts/java-exceptions/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Java Exceptions","name":"Java Exceptions","description":"Exception-handling 假如调用了一个不是自己写的方法, 该方法执行某些有风险的任务(当然,自己写的也可能会有风险),可能会在运行期间出状况,那么就必须认识到该方法是有风险的, 要写出可以在发生状况时做出应对的代码.\n当程序出现错误时，假如继续运行下去已经没有意义（或者根本不可能继续），那么我们就想要中断正常的控制流程 - throws an exception。\nThrowing Exceptions 比如当想从某ArrayMap中提取某个不存在的键值时, java自动抛出一个implicit exception\n$ java ExceptionDemo Exception in thread \u0026#34;main\u0026#34; java.lang.ArrayIndexOutOfBoundsException: -1 at ArrayMap.get(ArrayMap.java:38) at ExceptionDemo.main(ExceptionDemo.java:6) 如果想让自己的程序抛出更详细的信息, 可以在程序中加入explicit exception\npublic V get(K key) { intlocation = findKey(key); if(location \u0026lt; 0) { throw newIllegalArgumentException(\u0026#34;Key \u0026#34; + key + \u0026#34; does not exist in map.\u0026#34;\\); } return values[findKey(key)]; } $java ExceptionDemo Exception in thread \u0026#34;main\u0026#34; java.lang.IllegalArgumentException: Key yolp does not exist in map. at ArrayMap.get(ArrayMap.java:40) at ExceptionDemo.main(ExceptionDemo.java:6) Catch Exceptions 单纯 throw exception 会导致代码崩溃。但是通过 try - catch “捕捉”异常(RuntimeException 是 Java object), 可以防止程序崩溃。\n","keywords":["Java"],"articleBody":"Exception-handling 假如调用了一个不是自己写的方法, 该方法执行某些有风险的任务(当然,自己写的也可能会有风险),可能会在运行期间出状况,那么就必须认识到该方法是有风险的, 要写出可以在发生状况时做出应对的代码.\n当程序出现错误时，假如继续运行下去已经没有意义（或者根本不可能继续），那么我们就想要中断正常的控制流程 - throws an exception。\nThrowing Exceptions 比如当想从某ArrayMap中提取某个不存在的键值时, java自动抛出一个implicit exception\n$ java ExceptionDemo Exception in thread \"main\" java.lang.ArrayIndexOutOfBoundsException: -1 at ArrayMap.get(ArrayMap.java:38) at ExceptionDemo.main(ExceptionDemo.java:6) 如果想让自己的程序抛出更详细的信息, 可以在程序中加入explicit exception\npublic V get(K key) { intlocation = findKey(key); if(location \u003c 0) { throw newIllegalArgumentException(\"Key \" + key + \" does not exist in map.\"\\); } return values[findKey(key)]; } $java ExceptionDemo Exception in thread \"main\" java.lang.IllegalArgumentException: Key yolp does not exist in map. at ArrayMap.get(ArrayMap.java:40) at ExceptionDemo.main(ExceptionDemo.java:6) Catch Exceptions 单纯 throw exception 会导致代码崩溃。但是通过 try - catch “捕捉”异常(RuntimeException 是 Java object), 可以防止程序崩溃。\n比如通过捕捉异常, 来引入修正措施: 下面这个代码通过\n/** 当狗在生气时, 如果尝试拍拍它，会抛出一个 RuntimeException， 捕捉到 exception 后, 用香蕉来抚慰它. */ Dog d = new Dog(\"Lucy\", \"Retriever\", 80); d.becomeAngry(); try { // 把有风险的代码块放在try块 d.receivePat(); } catch (Exception e) { System.out.println( \"Tried to pat: \" + e); d.eatTreat(\"banana\"); } d.receivePat(); System.out.println(d); $ java ExceptionDemo Tried to pat: java.lang.RuntimeException: grrr... snarl snarl Lucy is a displeased Retriever weighing 80.0 standard lb units. $ java ExceptionDemo Tried to pat: java.lang.RuntimeException: grrr... snarl snarl Lucy munches the banana Lucy enjoys the pat. Lucy is a happy Retriever weighing 80.0 standard lb units. Exception 继承自 Throwable, 异常也是多态的。\npublic class Throwable extends Object implements Serializable The Throwable class is the superclass of all errors and exceptions in the Java language. Direct Known Subclasses: Error, Exception\n如果使用if else来管理异常会让代码变得很乱而难以阅读. 而使用try catch可以为每种类型的 exception 提供不同的应对。使代码像清晰的记述文般铺展开来: 首先，尝试执行所需的操作。然后，捕捉任何错误。\npublic class Laundry { public void doLaundry() throws PantsException, LingerieException {} } public class Foo { public void go() { Laundry laundry = new Laundry(); try { laundry.doLaundry(); } catch (PantsException pex) { // doSomething } catch (LingerieException lex) { //doSomething } } } 这种清晰度使代码的长期维护变得更容易。 以异常的父类来声明会抛出的异常, 这样就不必声明每个子类异常了, 在catch块中只需要捕捉异常的父类.\npublic void doLaundry() throws ClothingException {} try { laundry.doLaundry(); } catch (ClothingException cex) { } 但如果需要对每个不同的子类异常采取不同的措施, 那么还是需要声明各个子类异常, 并分别捕捉.\ntry { laundry.doLaundry(); } catch (LingerieException lex) { //doSomething } catch (ClothingException cex) { //doSomething } catch (Exception ex) { //doSomething } 此时多个catch块要从小排到大(在继承树上看, 就是先捕捉子类), 不能把父类异常放在子类上面,否则无法通过编译. 因为JVM只会从上开始往下找第一个符合范围的catch块, 如果第一个catch就是catch (Exception ex), 那么剩下的捕捉都没用了.\nFinally 在try-catch后面, 使用finally指示无论如何都要执行的部分(不管有没有异常).\ntry { turnOvenOn(); x.bake(); } catch (BakingException ex) { ex.printStackTrace(); } finally { // 不管怎样最后都要关火! turnOvenOff(); } 如果try块失败了, 抛出异常, 流程马上转移到catch块. 当catch块完成时, 继续执行finally块. 当finally块完成时, 继续执行其他代码 如果try块成功, 流程会跳过catch块并移动到finally. finally块完成时, 继续执行其他代码 即使try或者catch块中有return指令，finally还是会执行！， 流程会先暂时保存return的值，去执行finally, 然后再return. 但是, 如果finally中也有return指令，那么会直接执行该return指令，结束整个流程，这意味着try/catch中的return得不到执行, 且它的值会丢失. 如果不想处理异常 有些情况下, 比如某个异常是在你的程序调用的其他程序中抛出的, 你可以选择不处理这个异常, 把它duck掉, 让那些调用你方法的程序来处理这个异常. 也就说你的程序只是把异常转个手, 给个出路.\n// 只有抛出, 没有try/catch 异常 public void foo() throws ReallyBadException {} 方法抛出异常时, 方法会从栈上立即被取出, 而异常会再度丢给栈上的方法, 也就说下一个调用方, 这种过程可以一直循环下去. 但ducking只是在击鼓传花, 最后总得有个方法接盘, 如果连main()也duck掉, 那么就是Uncaught Exceptions Stack Trace, 异常到达堆栈底部后仍未被捕获，JVM崩溃，Java 打印出堆栈的跟踪:\njava.lang.RuntimeException in thread “main”: at ArrayRingBuffer.peek:63 at GuitarString.sample:48 at GuitarHeroLite.java:110 程序猿可以据此追踪错误路径。\nChecked vs Unchecked Exceptions 有时候，某些抛出的 exception 无法通过编译，可以理解为这些异常在编译器看来是非常恶心的存在，需要程序猿必须给这些 exception 提供明确的应对处理方案 - 这种叫 checked exception （“must be checked”）。这种异常是以人无法预测或防止的方法出现的执行期失败状况, 比如我们无法保证文件一直都在, 无法保证服务器不会死机.\npublic class Eagle { public static void gulgate() { if (today == “Thursday”) { throw new IOException(\"hi\"); } } } $ javac Eagle Eagle.java:4: error: unreported exception IOException; must be caught or declared to be thrown throw new IOException(\"hi\"); } ^ 很明显，Java对此IOException并不满意, 因为IOExceptions是 checked exception, 而这里没有提供应对处理方案。但假如换做RuntimeException就可以编译通过 (虽然在 runtime 时会崩溃). InterruptException也是要检查的异常. 大多数check exception都有修正的可能性。例如遇到FileNotFound，可以考虑要求用户重新指定他们想要的文件 (可能是因为错误输入导致的)。\nErrors 和 Runtime Exceptions, 以及它们的子类都是unchecked. 大部分RuntimeException都是因为程序逻辑的问题. 虽然check exception是人力无法保证, 但我们可以确保程序的逻辑不出错, 例如对只有长度N的数组中取第N+1个元素, 这种是逻辑错误了, 不存在什么补救, 而是应该在写代码时就要避免。try/catch是用来处理真正的异常, 而不是程序的逻辑错误.\nJava在尽最大努力确保每个程序运行时不会崩溃，所以它不会允许程序留下任何明明可以应对修正却没有被明确地修正的错误。\n两种方法来处理 checked error:\nCatch public static void gulgate() { try { if (today == “Thursday”) { throw new IOException(\"hi\"); } } catch (Exception e) { System.out.println(\"psych!\"); } } 假如能够应对，尽量用 catch 锁定异常防止其逃逸。 Specify: 如果实在不想在该方法中处理这种异常，可以将责任推迟到别的地方。我们可以指定该方法是危险的 public static void gulgate() throws IOException { ... throw new IOException(\"hi\"); ... } 然后任何其他调用`gulgate()`的方法也变成危险的了, 它们也需要被处理(同样使用两种方法之一) ```java // catch public static void main(String[] args) { try { gulgate(); } catch(IOException e) { System.out.println(\"Averted!\"); } } // 或 specify public static void main(String[] args) throws IOException { gulgate(); } ``` 需要明确异常处理责任人。同时确保调用者知道该方法是危险的！ 异常处理规则 catch和finally不能没有try try块和catch块之间不能有其他代码 try一定要有catch或finally 只带有finally而没有catch的try必须要声明异常, 也就是明确抛出void go() throws FooException {try {} finally {} } ","wordCount":"575","inLanguage":"en","datePublished":"2017-05-29T00:00:00Z","dateModified":"2017-05-29T00:00:00Z","author":{"@type":"Person","name":"Cong Chan"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://congchan.github.io/posts/java-exceptions/"},"publisher":{"@type":"Organization","name":"Cong's Log","logo":{"@type":"ImageObject","url":"https://congchan.github.io/favicons/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://congchan.github.io/ accesskey=h title="Cong's Log (Alt + H)">Cong's Log</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)" aria-label="Toggle theme">
<svg id="moon" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg>
<svg id="sun" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://congchan.github.io/archives title=Archive><span>Archive</span></a></li><li><a href=https://congchan.github.io/search/ title="Search (Alt + /)" accesskey=/><span>Search</span></a></li><li><a href=https://congchan.github.io/tags/ title=Tags><span>Tags</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://congchan.github.io/>Home</a>&nbsp;»&nbsp;<a href=https://congchan.github.io/posts/>Posts</a></div><h1 class="post-title entry-hint-parent">Java Exceptions</h1><div class=post-meta><span title='2017-05-29 00:00:00 +0000 UTC'>2017-05-29</span>&nbsp;·&nbsp;3 min&nbsp;·&nbsp;Cong Chan&nbsp;|&nbsp;<a href=https://github.com/%3cgitlab%20user%3e/%3crepo%20name%3e/tree/%3cbranch%20name%3e/%3cpath%20to%20content%3e//posts/java-exception.md rel="noopener noreferrer edit" target=_blank>Suggest Changes</a></div></header><div class=toc><details><summary accesskey=c title="(Alt + C)"><span class=details>Table of Contents</span></summary><div class=inner><ul><li><a href=#exception-handling aria-label=Exception-handling>Exception-handling</a><ul><li><a href=#throwing-exceptions aria-label="Throwing Exceptions">Throwing Exceptions</a></li><li><a href=#catch-exceptions aria-label="Catch Exceptions">Catch Exceptions</a></li><li><a href=#finally aria-label=Finally>Finally</a></li><li><a href=#%e5%a6%82%e6%9e%9c%e4%b8%8d%e6%83%b3%e5%a4%84%e7%90%86%e5%bc%82%e5%b8%b8 aria-label=如果不想处理异常>如果不想处理异常</a></li><li><a href=#checked-vs-unchecked-exceptions aria-label="Checked vs Unchecked Exceptions">Checked vs Unchecked Exceptions</a></li><li><a href=#%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e8%a7%84%e5%88%99 aria-label=异常处理规则>异常处理规则</a></li></ul></li></ul></div></details></div><div class=post-content><h2 id=exception-handling>Exception-handling<a hidden class=anchor aria-hidden=true href=#exception-handling>#</a></h2><p>假如调用了一个不是自己写的方法, 该方法执行某些有风险的任务(当然,自己写的也可能会有风险),可能会在运行期间出状况,那么就必须认识到该方法是有风险的, 要写出可以在发生状况时做出应对的代码.</p><p>当程序出现错误时，假如继续运行下去已经没有意义（或者根本不可能继续），那么我们就想要中断正常的控制流程 - throws an exception。</p><h3 id=throwing-exceptions>Throwing Exceptions<a hidden class=anchor aria-hidden=true href=#throwing-exceptions>#</a></h3><p>比如当想从某<code>ArrayMap</code>中提取某个不存在的键值时, java自动抛出一个<code>implicit exception</code></p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>$</span><span class=w> </span><span class=n>java</span><span class=w> </span><span class=n>ExceptionDemo</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Exception</span><span class=w> </span><span class=n>in</span><span class=w> </span><span class=n>thread</span><span class=w> </span><span class=s>&#34;main&#34;</span><span class=w> </span><span class=n>java</span><span class=p>.</span><span class=na>lang</span><span class=p>.</span><span class=na>ArrayIndexOutOfBoundsException</span><span class=p>:</span><span class=w> </span><span class=o>-</span><span class=n>1</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>ArrayMap</span><span class=p>.</span><span class=na>get</span><span class=p>(</span><span class=n>ArrayMap</span><span class=p>.</span><span class=na>java</span><span class=p>:</span><span class=n>38</span><span class=p>)</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>ExceptionDemo</span><span class=p>.</span><span class=na>main</span><span class=p>(</span><span class=n>ExceptionDemo</span><span class=p>.</span><span class=na>java</span><span class=p>:</span><span class=n>6</span><span class=p>)</span><span class=w>
</span></span></span></code></pre></div><p>如果想让自己的程序抛出更详细的信息, 可以在程序中加入<code>explicit exception</code></p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=n>V</span><span class=w> </span><span class=nf>get</span><span class=p>(</span><span class=n>K</span><span class=w> </span><span class=n>key</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>intlocation</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=n>findKey</span><span class=p>(</span><span class=n>key</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=k>if</span><span class=p>(</span><span class=n>location</span><span class=w> </span><span class=o>&lt;</span><span class=w> </span><span class=n>0</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=k>throw</span><span class=w> </span><span class=n>newIllegalArgumentException</span><span class=p>(</span><span class=s>&#34;Key &#34;</span><span class=w> </span><span class=o>+</span><span class=w> </span><span class=n>key</span><span class=w> </span><span class=o>+</span><span class=w> </span><span class=s>&#34; does not exist in map.&#34;</span><span class=err>\</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=k>return</span><span class=w> </span><span class=n>values</span><span class=o>[</span><span class=n>findKey</span><span class=p>(</span><span class=n>key</span><span class=p>)</span><span class=o>]</span><span class=p>;</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>$java</span><span class=w> </span><span class=n>ExceptionDemo</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Exception</span><span class=w> </span><span class=n>in</span><span class=w> </span><span class=n>thread</span><span class=w> </span><span class=s>&#34;main&#34;</span><span class=w> </span><span class=n>java</span><span class=p>.</span><span class=na>lang</span><span class=p>.</span><span class=na>IllegalArgumentException</span><span class=p>:</span><span class=w> </span><span class=n>Key</span><span class=w> </span><span class=n>yolp</span><span class=w> </span><span class=n>does</span><span class=w> </span><span class=n>not</span><span class=w> </span><span class=n>exist</span><span class=w> </span><span class=n>in</span><span class=w> </span><span class=n>map</span><span class=p>.</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>ArrayMap</span><span class=p>.</span><span class=na>get</span><span class=p>(</span><span class=n>ArrayMap</span><span class=p>.</span><span class=na>java</span><span class=p>:</span><span class=n>40</span><span class=p>)</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>ExceptionDemo</span><span class=p>.</span><span class=na>main</span><span class=p>(</span><span class=n>ExceptionDemo</span><span class=p>.</span><span class=na>java</span><span class=p>:</span><span class=n>6</span><span class=p>)</span><span class=w>
</span></span></span></code></pre></div><h3 id=catch-exceptions>Catch Exceptions<a hidden class=anchor aria-hidden=true href=#catch-exceptions>#</a></h3><p>单纯 throw exception 会导致代码崩溃。但是通过 <code>try - catch</code> “捕捉”异常(<code>RuntimeException</code> 是 Java object), 可以防止程序崩溃。</p><p>比如通过捕捉异常, 来引入修正措施: 下面这个代码通过</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=cm>/** 当狗在生气时, 如果尝试拍拍它，会抛出一个 RuntimeException，
</span></span></span><span class=line><span class=cl><span class=cm>捕捉到 exception 后, 用香蕉来抚慰它. */</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Dog</span><span class=w> </span><span class=n>d</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>Dog</span><span class=p>(</span><span class=s>&#34;Lucy&#34;</span><span class=p>,</span><span class=w> </span><span class=s>&#34;Retriever&#34;</span><span class=p>,</span><span class=w> </span><span class=n>80</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>d</span><span class=p>.</span><span class=na>becomeAngry</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>try</span><span class=w> </span><span class=p>{</span><span class=w> </span><span class=c1>// 把有风险的代码块放在try块</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>d</span><span class=p>.</span><span class=na>receivePat</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>Exception</span><span class=w> </span><span class=n>e</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>System</span><span class=p>.</span><span class=na>out</span><span class=p>.</span><span class=na>println</span><span class=p>(</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=s>&#34;Tried to pat: &#34;</span><span class=w> </span><span class=o>+</span><span class=w> </span><span class=n>e</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>d</span><span class=p>.</span><span class=na>eatTreat</span><span class=p>(</span><span class=s>&#34;banana&#34;</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>d</span><span class=p>.</span><span class=na>receivePat</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>System</span><span class=p>.</span><span class=na>out</span><span class=p>.</span><span class=na>println</span><span class=p>(</span><span class=n>d</span><span class=p>);</span><span class=w>
</span></span></span></code></pre></div><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>$</span><span class=w> </span><span class=n>java</span><span class=w> </span><span class=n>ExceptionDemo</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Tried</span><span class=w> </span><span class=n>to</span><span class=w> </span><span class=n>pat</span><span class=p>:</span><span class=w> </span><span class=n>java</span><span class=p>.</span><span class=na>lang</span><span class=p>.</span><span class=na>RuntimeException</span><span class=p>:</span><span class=w> </span><span class=n>grrr</span><span class=p>...</span><span class=w> </span><span class=n>snarl</span><span class=w> </span><span class=n>snarl</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Lucy</span><span class=w> </span><span class=n>is</span><span class=w> </span><span class=n>a</span><span class=w> </span><span class=n>displeased</span><span class=w> </span><span class=n>Retriever</span><span class=w> </span><span class=n>weighing</span><span class=w> </span><span class=n>80</span><span class=p>.</span><span class=na>0</span><span class=w> </span><span class=n>standard</span><span class=w> </span><span class=n>lb</span><span class=w> </span><span class=n>units</span><span class=p>.</span><span class=w>
</span></span></span></code></pre></div><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>$</span><span class=w> </span><span class=n>java</span><span class=w> </span><span class=n>ExceptionDemo</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Tried</span><span class=w> </span><span class=n>to</span><span class=w> </span><span class=n>pat</span><span class=p>:</span><span class=w> </span><span class=n>java</span><span class=p>.</span><span class=na>lang</span><span class=p>.</span><span class=na>RuntimeException</span><span class=p>:</span><span class=w> </span><span class=n>grrr</span><span class=p>...</span><span class=w> </span><span class=n>snarl</span><span class=w> </span><span class=n>snarl</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Lucy</span><span class=w> </span><span class=n>munches</span><span class=w> </span><span class=n>the</span><span class=w> </span><span class=n>banana</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Lucy</span><span class=w> </span><span class=n>enjoys</span><span class=w> </span><span class=n>the</span><span class=w> </span><span class=n>pat</span><span class=p>.</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Lucy</span><span class=w> </span><span class=n>is</span><span class=w> </span><span class=n>a</span><span class=w> </span><span class=n>happy</span><span class=w> </span><span class=n>Retriever</span><span class=w> </span><span class=n>weighing</span><span class=w> </span><span class=n>80</span><span class=p>.</span><span class=na>0</span><span class=w> </span><span class=n>standard</span><span class=w> </span><span class=n>lb</span><span class=w> </span><span class=n>units</span><span class=p>.</span><span class=w>
</span></span></span></code></pre></div><p>Exception 继承自 <code>Throwable</code>, 异常也是多态的。</p><pre tabindex=0><code>public class Throwable extends Object implements Serializable
</code></pre><blockquote><p>The Throwable class is the superclass of all errors and exceptions in the Java language. Direct Known Subclasses: Error, Exception</p></blockquote><p>如果使用<code>if else</code>来管理异常会让代码变得很乱而难以阅读. 而使用<code>try catch</code>可以为每种类型的 exception 提供不同的应对。使代码像清晰的记述文般铺展开来: 首先，尝试执行所需的操作。然后，捕捉任何错误。</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=kd>class</span> <span class=nc>Laundry</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>public</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>doLaundry</span><span class=p>()</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>PantsException</span><span class=p>,</span><span class=w> </span><span class=n>LingerieException</span><span class=w> </span><span class=p>{}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=kd>public</span><span class=w> </span><span class=kd>class</span> <span class=nc>Foo</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>public</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>go</span><span class=p>()</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=n>Laundry</span><span class=w> </span><span class=n>laundry</span><span class=w> </span><span class=o>=</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>Laundry</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=k>try</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>            </span><span class=n>laundry</span><span class=p>.</span><span class=na>doLaundry</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>PantsException</span><span class=w> </span><span class=n>pex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>            </span><span class=c1>// doSomething</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>LingerieException</span><span class=w> </span><span class=n>lex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>            </span><span class=c1>//doSomething</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><p>这种清晰度使代码的长期维护变得更容易。
以异常的父类来声明会抛出的异常, 这样就不必声明每个子类异常了, 在<code>catch</code>块中只需要捕捉异常的父类.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>doLaundry</span><span class=p>()</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>ClothingException</span><span class=w> </span><span class=p>{}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>try</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>laundry</span><span class=p>.</span><span class=na>doLaundry</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>ClothingException</span><span class=w> </span><span class=n>cex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><p>但如果需要对每个不同的子类异常采取不同的措施, 那么还是需要声明各个子类异常, 并分别捕捉.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=k>try</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>laundry</span><span class=p>.</span><span class=na>doLaundry</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>LingerieException</span><span class=w> </span><span class=n>lex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=c1>//doSomething</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>ClothingException</span><span class=w> </span><span class=n>cex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=c1>//doSomething</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>Exception</span><span class=w> </span><span class=n>ex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=c1>//doSomething</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><p>此时多个<code>catch</code>块要从小排到大(在继承树上看, 就是先捕捉子类), <strong>不能把父类异常放在子类上面,否则无法通过编译</strong>. 因为JVM只会从上开始往下找第一个符合范围的catch块, 如果第一个catch就是<code>catch (Exception ex)</code>, 那么剩下的捕捉都没用了.</p><h3 id=finally>Finally<a hidden class=anchor aria-hidden=true href=#finally>#</a></h3><p>在<code>try-catch</code>后面, 使用<code>finally</code>指示无论如何都要执行的部分(不管有没有异常).</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=k>try</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>turnOvenOn</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>x</span><span class=p>.</span><span class=na>bake</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>BakingException</span><span class=w> </span><span class=n>ex</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>ex</span><span class=p>.</span><span class=na>printStackTrace</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w> </span><span class=k>finally</span><span class=w> </span><span class=p>{</span><span class=w> </span><span class=c1>// 不管怎样最后都要关火!</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=n>turnOvenOff</span><span class=p>();</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><ul><li>如果<code>try</code>块失败了, 抛出异常, 流程马上转移到<code>catch</code>块. 当<code>catch</code>块完成时, 继续执行<code>finally</code>块. 当<code>finally</code>块完成时, 继续执行其他代码</li><li>如果<code>try</code>块成功, 流程会跳过<code>catch</code>块并移动到<code>finally</code>. <code>finally</code>块完成时, 继续执行其他代码</li><li><strong>即使try或者catch块中有return指令，finally还是会执行！</strong>， 流程会先暂时保存<code>return</code>的值，去执行<code>finally</code>, 然后再<code>return</code>.</li><li>但是, <strong>如果finally中也有return指令，那么会直接执行该return指令，结束整个流程</strong>，这意味着<code>try/catch</code>中的<code>return</code>得不到执行, 且它的值会丢失.</li></ul><h3 id=如果不想处理异常>如果不想处理异常<a hidden class=anchor aria-hidden=true href=#如果不想处理异常>#</a></h3><p>有些情况下, 比如某个异常是在你的程序调用的其他程序中抛出的, 你可以选择不处理这个异常, 把它<code>duck</code>掉, 让那些调用你方法的程序来处理这个异常. 也就说你的程序只是把异常转个手, 给个出路.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=c1>// 只有抛出, 没有try/catch 异常</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=kd>public</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>foo</span><span class=p>()</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>ReallyBadException</span><span class=w> </span><span class=p>{}</span><span class=w>
</span></span></span></code></pre></div><p>方法抛出异常时, 方法会从栈上立即被取出, 而异常会再度丢给栈上的方法, 也就说下一个调用方, 这种过程可以一直循环下去. 但ducking只是在击鼓传花, 最后总得有个方法接盘, 如果连<code>main()</code>也duck掉, 那么就是<code>Uncaught Exceptions Stack Trace</code>, 异常到达堆栈底部后仍未被捕获，JVM崩溃，Java 打印出堆栈的跟踪:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>java</span><span class=p>.</span><span class=na>lang</span><span class=p>.</span><span class=na>RuntimeException</span><span class=w> </span><span class=n>in</span><span class=w> </span><span class=n>thread</span><span class=w> </span><span class=err>“</span><span class=n>main</span><span class=err>”</span><span class=p>:</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>ArrayRingBuffer</span><span class=p>.</span><span class=na>peek</span><span class=p>:</span><span class=n>63</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>GuitarString</span><span class=p>.</span><span class=na>sample</span><span class=p>:</span><span class=n>48</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>at</span><span class=w> </span><span class=n>GuitarHeroLite</span><span class=p>.</span><span class=na>java</span><span class=p>:</span><span class=n>110</span><span class=w>
</span></span></span></code></pre></div><p><img loading=lazy src=https://joshhug.gitbooks.io/hug61b/content/assets/callstack.png title="image from: https://joshhug.gitbooks.io/hug61b">
程序猿可以据此追踪错误路径。</p><h3 id=checked-vs-unchecked-exceptions>Checked vs Unchecked Exceptions<a hidden class=anchor aria-hidden=true href=#checked-vs-unchecked-exceptions>#</a></h3><p>有时候，某些抛出的 exception 无法通过编译，可以理解为这些异常在编译器看来是非常恶心的存在，需要程序猿必须给这些 exception 提供明确的应对处理方案 - 这种叫 checked exception （&ldquo;must be checked&rdquo;）。这种异常是以人无法预测或防止的方法出现的执行期失败状况, 比如我们无法保证文件一直都在, 无法保证服务器不会死机.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=kd>class</span> <span class=nc>Eagle</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=kd>public</span><span class=w> </span><span class=kd>static</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>gulgate</span><span class=p>()</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=k>if</span><span class=w> </span><span class=p>(</span><span class=n>today</span><span class=w> </span><span class=o>==</span><span class=w> </span><span class=err>“</span><span class=n>Thursday</span><span class=err>”</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>            </span><span class=k>throw</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>IOException</span><span class=p>(</span><span class=s>&#34;hi&#34;</span><span class=p>);</span><span class=w> </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=n>$</span><span class=w> </span><span class=n>javac</span><span class=w> </span><span class=n>Eagle</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=n>Eagle</span><span class=p>.</span><span class=na>java</span><span class=p>:</span><span class=n>4</span><span class=p>:</span><span class=w> </span><span class=n>error</span><span class=p>:</span><span class=w> </span><span class=n>unreported</span><span class=w> </span><span class=n>exception</span><span class=w> </span><span class=n>IOException</span><span class=p>;</span><span class=w> </span><span class=n>must</span><span class=w> </span><span class=n>be</span><span class=w> </span><span class=n>caught</span><span class=w> </span><span class=n>or</span><span class=w> </span><span class=n>declared</span><span class=w> </span><span class=n>to</span><span class=w> </span><span class=n>be</span><span class=w> </span><span class=n>thrown</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=k>throw</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=nf>IOException</span><span class=p>(</span><span class=s>&#34;hi&#34;</span><span class=p>);</span><span class=w> </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=o>^</span><span class=w>
</span></span></span></code></pre></div><p>很明显，Java对此<code>IOException</code>并不满意, 因为<code>IOExceptions</code>是 checked exception, 而这里没有提供应对处理方案。但假如换做<code>RuntimeException</code>就可以编译通过 (虽然在 runtime 时会崩溃).<img loading=lazy src=https://joshhug.gitbooks.io/hug61b/content/assets/checked_exceptions.png title="image from: https://joshhug.gitbooks.io/hug61b/"> <code>InterruptException</code>也是要检查的异常. 大多数<code>check exception</code>都有修正的可能性。例如遇到<code>FileNotFound</code>，可以考虑要求用户重新指定他们想要的文件 (可能是因为错误输入导致的)。</p><p><code>Errors</code> 和 <code>Runtime Exceptions</code>, 以及它们的子类都是<code>unchecked</code>. 大部分<code>RuntimeException</code>都是因为程序逻辑的问题. 虽然<code>check exception</code>是人力无法保证, 但我们可以确保程序的逻辑不出错, 例如对只有长度N的数组中取第<code>N+1</code>个元素, 这种是逻辑错误了, 不存在什么补救, 而是应该在写代码时就要避免。<code>try/catch</code>是用来处理真正的异常, 而不是程序的逻辑错误.</p><p>Java在尽最大努力确保每个程序运行时不会崩溃，所以它不会允许程序留下任何明明可以应对修正却没有被明确地修正的错误。</p><p>两种方法来处理 checked error:</p><ol><li><strong>Catch</strong></li></ol><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=kd>static</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>gulgate</span><span class=p>()</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=k>try</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=k>if</span><span class=w> </span><span class=p>(</span><span class=n>today</span><span class=w> </span><span class=o>==</span><span class=w> </span><span class=err>“</span><span class=n>Thursday</span><span class=err>”</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>            </span><span class=k>throw</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>IOException</span><span class=p>(</span><span class=s>&#34;hi&#34;</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w> </span><span class=k>catch</span><span class=w> </span><span class=p>(</span><span class=n>Exception</span><span class=w> </span><span class=n>e</span><span class=p>)</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>        </span><span class=n>System</span><span class=p>.</span><span class=na>out</span><span class=p>.</span><span class=na>println</span><span class=p>(</span><span class=s>&#34;psych!&#34;</span><span class=p>);</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>}</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><pre><code>假如能够应对，尽量用 catch 锁定异常防止其逃逸。
</code></pre><ol start=2><li><strong>Specify</strong>: 如果实在不想在该方法中处理这种异常，可以将责任推迟到别的地方。我们可以指定该方法是危险的</li></ol><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span><span class=w> </span><span class=kd>static</span><span class=w> </span><span class=kt>void</span><span class=w> </span><span class=nf>gulgate</span><span class=p>()</span><span class=w> </span><span class=kd>throws</span><span class=w> </span><span class=n>IOException</span><span class=w> </span><span class=p>{</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w>    </span><span class=p>...</span><span class=w> </span><span class=k>throw</span><span class=w> </span><span class=k>new</span><span class=w> </span><span class=n>IOException</span><span class=p>(</span><span class=s>&#34;hi&#34;</span><span class=p>);</span><span class=w> </span><span class=p>...</span><span class=w>
</span></span></span><span class=line><span class=cl><span class=w></span><span class=p>}</span><span class=w>
</span></span></span></code></pre></div><pre><code>然后任何其他调用`gulgate()`的方法也变成危险的了, 它们也需要被处理(同样使用两种方法之一)
```java
// catch
public static void main(String[] args) {
    try {
        gulgate();
    } catch(IOException e) {
        System.out.println(&quot;Averted!&quot;);
    }
}
// 或 specify
public static void main(String[] args) throws IOException {
    gulgate();
}
```
需要明确异常处理责任人。同时确保调用者知道该方法是危险的！
</code></pre><h3 id=异常处理规则>异常处理规则<a hidden class=anchor aria-hidden=true href=#异常处理规则>#</a></h3><ol><li>catch和finally不能没有try</li><li>try块和catch块之间不能有其他代码</li><li>try一定要有catch或finally</li><li>只带有finally而没有catch的try必须要声明异常, 也就是明确抛出<code>void go() throws FooException {try {} finally {} }</code></li></ol></div><footer class=post-footer><ul class=post-tags><li><a href=https://congchan.github.io/tags/java/>Java</a></li></ul><nav class=paginav><a class=prev href=https://congchan.github.io/posts/java-%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6/><span class=title>« Prev</span><br><span>Java 垃圾回收机制</span>
</a><a class=next href=https://congchan.github.io/posts/java-immutability/><span class=title>Next »</span><br><span>Java Immutability</span></a></nav><ul class=share-buttons><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on x" href="https://x.com/intent/tweet/?text=Java%20Exceptions&amp;url=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f&amp;hashtags=Java"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentColor"><path d="M512 62.554V449.446C512 483.97 483.97 512 449.446 512H62.554C28.03 512 0 483.97.0 449.446V62.554C0 28.03 28.029.0 62.554.0H449.446C483.971.0 512 28.03 512 62.554zM269.951 190.75 182.567 75.216H56L207.216 272.95 63.9 436.783h61.366L235.9 310.383l96.667 126.4H456L298.367 228.367l134-153.151H371.033zM127.633 110h36.468l219.38 290.065H349.5z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on linkedin" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f&amp;title=Java%20Exceptions&amp;summary=Java%20Exceptions&amp;source=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentColor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM160.461 423.278V197.561h-75.04v225.717h75.04zm270.539.0V293.839c0-69.333-37.018-101.586-86.381-101.586-39.804.0-57.634 21.891-67.617 37.266v-31.958h-75.021c.995 21.181.0 225.717.0 225.717h75.02V297.222c0-6.748.486-13.492 2.474-18.315 5.414-13.475 17.767-27.434 38.494-27.434 27.135.0 38.007 20.707 38.007 51.037v120.768H431zM123.448 88.722C97.774 88.722 81 105.601 81 127.724c0 21.658 16.264 39.002 41.455 39.002h.484c26.165.0 42.452-17.344 42.452-39.002-.485-22.092-16.241-38.954-41.943-39.002z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on reddit" href="https://reddit.com/submit?url=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f&title=Java%20Exceptions"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentColor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM446 265.638c0-22.964-18.616-41.58-41.58-41.58-11.211.0-21.361 4.457-28.841 11.666-28.424-20.508-67.586-33.757-111.204-35.278l18.941-89.121 61.884 13.157c.756 15.734 13.642 28.29 29.56 28.29 16.407.0 29.706-13.299 29.706-29.701.0-16.403-13.299-29.702-29.706-29.702-11.666.0-21.657 6.792-26.515 16.578l-69.105-14.69c-1.922-.418-3.939-.042-5.585 1.036-1.658 1.073-2.811 2.761-3.224 4.686l-21.152 99.438c-44.258 1.228-84.046 14.494-112.837 35.232-7.468-7.164-17.589-11.591-28.757-11.591-22.965.0-41.585 18.616-41.585 41.58.0 16.896 10.095 31.41 24.568 37.918-.639 4.135-.99 8.328-.99 12.576.0 63.977 74.469 115.836 166.33 115.836s166.334-51.859 166.334-115.836c0-4.218-.347-8.387-.977-12.493 14.564-6.47 24.735-21.034 24.735-38.001zM326.526 373.831c-20.27 20.241-59.115 21.816-70.534 21.816-11.428.0-50.277-1.575-70.522-21.82-3.007-3.008-3.007-7.882.0-10.889 3.003-2.999 7.882-3.003 10.885.0 12.777 12.781 40.11 17.317 59.637 17.317 19.522.0 46.86-4.536 59.657-17.321 3.016-2.999 7.886-2.995 10.885.008 3.008 3.011 3.003 7.882-.008 10.889zm-5.23-48.781c-16.373.0-29.701-13.324-29.701-29.698.0-16.381 13.328-29.714 29.701-29.714 16.378.0 29.706 13.333 29.706 29.714.0 16.374-13.328 29.698-29.706 29.698zM160.91 295.348c0-16.381 13.328-29.71 29.714-29.71 16.369.0 29.689 13.329 29.689 29.71.0 16.373-13.32 29.693-29.689 29.693-16.386.0-29.714-13.32-29.714-29.693z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on facebook" href="https://facebook.com/sharer/sharer.php?u=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentColor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H342.978V319.085h66.6l12.672-82.621h-79.272v-53.617c0-22.603 11.073-44.636 46.58-44.636H425.6v-70.34s-32.71-5.582-63.982-5.582c-65.288.0-107.96 39.569-107.96 111.204v62.971h-72.573v82.621h72.573V512h-191.104c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on whatsapp" href="https://api.whatsapp.com/send?text=Java%20Exceptions%20-%20https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f"><svg viewBox="0 0 512 512" height="30" width="30" fill="currentColor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zm-58.673 127.703c-33.842-33.881-78.847-52.548-126.798-52.568-98.799.0-179.21 80.405-179.249 179.234-.013 31.593 8.241 62.428 23.927 89.612l-25.429 92.884 95.021-24.925c26.181 14.28 55.659 21.807 85.658 21.816h.074c98.789.0 179.206-80.413 179.247-179.243.018-47.895-18.61-92.93-52.451-126.81zM263.976 403.485h-.06c-26.734-.01-52.954-7.193-75.828-20.767l-5.441-3.229-56.386 14.792 15.05-54.977-3.542-5.637c-14.913-23.72-22.791-51.136-22.779-79.287.033-82.142 66.867-148.971 149.046-148.971 39.793.014 77.199 15.531 105.329 43.692 28.128 28.16 43.609 65.592 43.594 105.4-.034 82.149-66.866 148.983-148.983 148.984zm81.721-111.581c-4.479-2.242-26.499-13.075-30.604-14.571-4.105-1.495-7.091-2.241-10.077 2.241-2.986 4.483-11.569 14.572-14.182 17.562-2.612 2.988-5.225 3.364-9.703 1.12-4.479-2.241-18.91-6.97-36.017-22.23C231.8 264.15 222.81 249.484 220.198 245s-.279-6.908 1.963-9.14c2.016-2.007 4.48-5.232 6.719-7.847 2.24-2.615 2.986-4.484 4.479-7.472 1.493-2.99.747-5.604-.374-7.846-1.119-2.241-10.077-24.288-13.809-33.256-3.635-8.733-7.327-7.55-10.077-7.688-2.609-.13-5.598-.158-8.583-.158-2.986.0-7.839 1.121-11.944 5.604-4.105 4.484-15.675 15.32-15.675 37.364.0 22.046 16.048 43.342 18.287 46.332 2.24 2.99 31.582 48.227 76.511 67.627 10.685 4.615 19.028 7.371 25.533 9.434 10.728 3.41 20.492 2.929 28.209 1.775 8.605-1.285 26.499-10.833 30.231-21.295 3.732-10.464 3.732-19.431 2.612-21.298-1.119-1.869-4.105-2.99-8.583-5.232z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on telegram" href="https://telegram.me/share/url?text=Java%20Exceptions&amp;url=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f"><svg viewBox="2 2 28 28" height="30" width="30" fill="currentColor"><path d="M26.49 29.86H5.5a3.37 3.37.0 01-2.47-1 3.35 3.35.0 01-1-2.47V5.48A3.36 3.36.0 013 3 3.37 3.37.0 015.5 2h21A3.38 3.38.0 0129 3a3.36 3.36.0 011 2.46V26.37a3.35 3.35.0 01-1 2.47 3.38 3.38.0 01-2.51 1.02zm-5.38-6.71a.79.79.0 00.85-.66L24.73 9.24a.55.55.0 00-.18-.46.62.62.0 00-.41-.17q-.08.0-16.53 6.11a.59.59.0 00-.41.59.57.57.0 00.43.52l4 1.24 1.61 4.83a.62.62.0 00.63.43.56.56.0 00.4-.17L16.54 20l4.09 3A.9.9.0 0021.11 23.15zM13.8 20.71l-1.21-4q8.72-5.55 8.78-5.55c.15.0.23.0.23.16a.18.18.0 010 .06s-2.51 2.3-7.52 6.8z"/></svg></a></li><li><a target=_blank rel="noopener noreferrer" aria-label="share Java Exceptions on ycombinator" href="https://news.ycombinator.com/submitlink?t=Java%20Exceptions&u=https%3a%2f%2fcongchan.github.io%2fposts%2fjava-exceptions%2f"><svg width="30" height="30" viewBox="0 0 512 512" fill="currentColor"><path d="M449.446.0C483.971.0 512 28.03 512 62.554V449.446C512 483.97 483.97 512 449.446 512H62.554C28.03 512 0 483.97.0 449.446V62.554C0 28.03 28.029.0 62.554.0H449.446zM183.8767 87.9921h-62.034L230.6673 292.4508V424.0079h50.6655V292.4508L390.1575 87.9921H328.1233L256 238.2489z"/></svg></a></li></ul></footer></article></main><footer class=footer><span>&copy; 2025 <a href=https://congchan.github.io/>Cong's Log</a></span> ·
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
<a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg viewBox="0 0 12 6" fill="currentColor"><path d="M12 6H0l6-6z"/></svg>
</a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script><script>document.querySelectorAll("pre > code").forEach(e=>{const n=e.parentNode.parentNode,t=document.createElement("button");t.classList.add("copy-code"),t.innerHTML="copy";function s(){t.innerHTML="copied!",setTimeout(()=>{t.innerHTML="copy"},2e3)}t.addEventListener("click",t=>{if("clipboard"in navigator){navigator.clipboard.writeText(e.textContent),s();return}const n=document.createRange();n.selectNodeContents(e);const o=window.getSelection();o.removeAllRanges(),o.addRange(n);try{document.execCommand("copy"),s()}catch{}o.removeRange(n)}),n.classList.contains("highlight")?n.appendChild(t):n.parentNode.firstChild==n||(e.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?e.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(t):e.parentNode.appendChild(t))})</script></body></html>